# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180122_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
