# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180124_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='backgroundimageone',
            new_name='backgroundimage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='backgroundimagethree',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='backgroundimagetwo',
        ),
    ]
