# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180127_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='card1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='imageendsub',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='imagemidsub',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='para1heading',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='para1sub',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='para2heading',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='para2sub',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcomesub',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
