# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180127_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='welcomesub',
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcomesubafterhighlight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcomesubforhighlight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcomesubhighlight',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
