# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180127_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='welcome',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='welcomesubafterhighlight',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='welcomesubforhighlight',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='welcomesubhighlight',
        ),
        migrations.AddField(
            model_name='homepage',
            name='subafterhighlight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subforhighlight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subhighlight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcomeheading',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
