# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180127_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='card1',
            new_name='card1text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='card2',
            new_name='card2text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='card3',
            new_name='card3text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='card1heading',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card2heading',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card3heading',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
