# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180129_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressumpage',
            old_name='text',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='heading1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='heading2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='heading3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='heading4',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='heading5',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='text1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='text3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='text4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impressumpage',
            name='text5',
            field=models.TextField(blank=True),
        ),
    ]
