# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 18:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180129_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressumpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
