# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
