# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('maintext', models.TextField(blank=True)),
                ('info1', models.TextField(blank=True)),
                ('info2', models.TextField(blank=True)),
                ('info3', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
